name: 'sample_fund_analytics'
version: '1.0.0'
config-version: 2

profile: 'sample_fund_analytics'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  sample_fund_analytics:
    +schema: raw

models:
  sample_fund_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
